# This is an EXAMPLE of using winvoice-gui

include:
  - path: 'https://github.com/Iron-E/winvoice-server.git#v0.6.4'
    project_directory: '.'

name: 'winvoice'

secrets:
  proxy-ssl: {file: 'config/proxy/ssl/'}
  proxy-ssl-cadir: {file: 'config/proxy/ssl-cadir/'}

networks:
  frontend: null

services:
  gui:
    image: 'winvoice-gui:${WINVOICE_GUI_TAG:-0.1.0}'
    build: '.'

    depends_on:
      server: {condition: 'service_healthy'}
    healthcheck:
      test: ['CMD', 'curl', '-fs', 'http://gui:3000']
      interval: '10s'
      timeout: '5s'
      retries: 5
    restart: 'always'

    environment:
      NODE_ENV: 'production'
      VIRTUAL_HOST: '${VIRTUAL_HOST:-localhost}'
      VIRTUAL_PORT: '${VIRTUAL_PORT:-3000}'

    networks: ['frontend']

  proxy:
    image: 'nginxproxy/nginx-proxy:1.4-alpine'

    depends_on:
      gui: {condition: 'service_healthy'}
    healthcheck:
      test: ['CMD', 'curl', '-fs', 'https://localhost:443']
      interval: '10s'
      timeout: '5s'
      retries: 5
    restart: 'always'

    secrets:
      - source: 'proxy-ssl'
        target: '/etc/nginx/certs'
      - source: 'proxy-ssl-cadir'
        target: '/etc/ssl/certs'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'

    networks: ['frontend']
    ports: ['80:80', '443:443']
