# This is an EXAMPLE of using winvoice-gui

include:
  - path: 'https://github.com/Iron-E/winvoice-server.git#v0.6.2'
    project_directory: '.'

name: 'winvoice'

networks:
  frontend: null

services:
  gui:
    image: 'winvoice/gui:${WINVOICE_GUI_TAG:-v0.1.0}'
    build: '.'

    depends_on:
      server: {condition: 'service_healthy'}
    healthcheck:
      test: ['CMD', 'curl', '-fs', 'http://gui:3000']
      interval: '10s'
      timeout: '5s'
      retries: 5
    restart: 'always'

    networks: ['frontend']

    environment:
      NODE_ENV: 'production'
