# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: 'v1'
kind: 'Secret'
metadata: &metadata
  labels: &labels
    app.kubernetes.io/name: &appName 'winvoice-gui'
    app.kubernetes.io/version: &appVersion '0.2.0'
    app.kubernetes.io/component: 'frontend'
    app.kubernetes.io/part-of: &projectName 'winvoice'
  namespace: &namespace 'example'
  name: 'winvoice.frontend.cors'
type: 'Opaque' # see https://kubernetes.io/docs/concepts/configuration/secret/#secret-types
data:
  allow.txt: 'aHR0cHM6Ly8qCg=='
---
